project_id = "gmflpmcepempcygdrayv"

[functions.chat]
verify_jwt = false

[functions.chat-study]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-section-image]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.youtube-videos]
verify_jwt = false

[functions.analyze-sentiment]
verify_jwt = false

[functions.sentiment-alert]
verify_jwt = false

[functions.generate-history-image]
verify_jwt = false