project_id = "gmflpmcepempcygdrayv"

[functions.chat]
verify_jwt = false

[functions.health-chat]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.youtube-videos]
verify_jwt = false

[functions.check-credits-preload]
verify_jwt = false